import { Inter } from "next/font/google";
import "./globals.css";
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Akeshya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
